version: '3.4'

services:
  apibank.web:
    image: ${DOCKER_REGISTRY-}apibankweb
    build:
      context: .
      dockerfile: src/ApiBank.Web/Dockerfile

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest    
    container_name: "SqlServerDB"
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "14330:1433"
    volumes:
      - C:\Dados\Volumes\sqlserver:/var/opt/mssql/data

# Add docker-compose: https://learn.microsoft.com/pt-br/visualstudio/containers/tutorial-multicontainer?view=vs-2022